#!/usr/bin/env python
#coding:utf-8
#Cisco IPSec VPN连接器, 可帮助你从列表中自动选服务器并连接, 若丢包率大于35%自动切换.
#运行在Linux下,且需要你安装好vpnc客户端, 实现有一个完整的配置文件/etc/vpnc.conf.
#运行方式: nohup vpnc_connector.py &
#日志默认路径:/var/log/vpn_connector.log.
#脚本中用到的pyping, tendo模块可用pip安装; psutil请升级到最新版.
#2017.10.14
import logging
import os
import psutil
import pyping
import random
import time
import tendo.singleton


logging.basicConfig(
    level = logging.WARNING,
    format = '%(asctime)s : %(levelname)s : %(message)s',
    filename = '/var/log/vpn_connector.log',
    filemode = 'a'
)
me = tendo.singleton.SingleInstance() #确保脚本是单例运行


def nic_tester():
    """
    检查网卡数和名字,确认vpn是否已连接,若你有两块及以上网卡,请将下面的数字都+1
    """
    nic = psutil.net_if_addrs()
    nics = ' '.join([k for k in nic.keys()])
    if len(nic) == 2:
        return False
    elif len(nic) == 3 and 'tun' in nics:
        return True
    elif len(nic) > 3:
        return 'BAD'


def net_pkg_lose_too_much():
    """
    丢包率检测器
    """
    try:
        res_ping = pyping.ping('8.8.8.8', count=20)
        return  res_ping.packet_lost / 20.00
    except Exception as e:
        logging.warning(e)


def connector(ip, connect=True):
    """
    VPN连接器
    """
    try:
        if not connect:
            logging.warning('>>>开始断开VPN...')
            os.system('/usr/sbin/vpnc-disconnect')
        else:
            logging.warning('>>>正在连接%s ...' % ip)
            os.system('/usr/sbin/vpnc --gateway %s /etc/vpnc.conf' % ip)
    except Exception as e:
        logging.warning(e)


def main(ip_addrs):
    if nic_tester():
        logging.warning('VPN当前在线')
    while True:
        online = nic_tester()
        if not online:
            logging.warning('>>>启动VPN...')
            connector(ip_addrs[random.randrange(0, 10)])
            time.sleep(5)
            if nic_tester():
                logging.warning('VPN已在线')
                time.sleep(180)
        elif online == 'BAD':
            logging.warning('>>>正在重启VPN...')
            os.system('service network restart')
            continue

        pkg_lose_rate = net_pkg_lose_too_much()
        if nic_tester() and pkg_lose_rate > 0.35:
            logging.warning('>>>VPN在线但丢包率过高,为:%s, 需更换VPN服务器' % pkg_lose_rate)
            connector(ip_addrs[random.randrange(0, 10)], connect=False)
            continue



if __name__ == '__main__':
    ip_addrs = [
        '172.x.x.130',
        '172.x.178.x',
        'x.164.201.131',
        'x.230.219.215',
        'x.162.70.121'
    ]
    main(ip_addrs)
